---
- name: install Https
  hosts: APP
  remote_user: root

  tasks:
   # - name: Install httpd
   #   yum: name=httpd state=present
   # - name: start the httpd
   #   service: name=httpd state=started
   # - name: Copy indexfile
   #   copy: src=/root/index.html dest=/var/www/html/index.html mode=644
    - name: Ansible Register
      shell: "find *.txt"
      args:
        chdir: "/opt/"
      register: find_output
    - debug:
        var: find_output

    - shell: "cp {{ item }} {{item}}_bkp"
      args:
        chdir: "/opt/"
      with_items:
         - "{{ find_output.stdout_lines }}"
...

