- name: Install prerequisites
  yum: name={{ item }} state=present
  with_items:
    - git
    - ntp
    - vim
    - httpd
- name: add a ascript
  file: path=/opt/ve.txt state=touch
  when:
   - ansible_hostname=="REMOTESERVER"
